### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by vkrishna-1** [INFO-526-FA24/project-2-data-detectivities#1]
The following is the peer review of the project proposal by data-detectivities. The team members that participated in this review are 

- Sai Kumar Bollam - @SaikumarBollam
- Vamsi Krishna Chagarlamudi - @vkrishna

- Describe the goal of the project.
The main goal of this project is to look at mass shooting incidents in the U.S. and try to find patterns, correlations, or trends related to time, location, demographics, and other factors. By doing this, the project hopes to give insights that could help public safety efforts or inform policies to reduce these incidents.

- Describe the data used or collected.
The project will use several datasets with detailed information about mass shooting events. Key datasets include mass_killing_incidents_public.csv, mass_killing_offenders_public.csv, mass_killing_victims_public.csv, and mass_killing_weapons_public.csv. These datasets have information on things like location of incidents, numbers of victims, demographics of shooters, weapon types, and more.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The project will use statistical analysis and data visualizations to answer the research questions. For example:
  - Trends over time and geographic areas affected will be shown using line charts, heatmaps, and maps.
  - Patterns related to shooter characteristics and incident severity will be explored with box plots, correlation plots, and density plots.
  - Time series analysis may help find any repeating patterns in incident timing.
  - External factors like gun ownership rates will be compared across states using maps and bubble charts.

- Is there anything that is unclear from the proposal?
  - It’s not clear if state-level factors like gun ownership rates will be added as a new dataset or if this information will come from somewhere specific.
  - The proposal doesn’t mention how they will deal with missing data, which might be an issue since the data is from several different sources.
  - It would also help to know exactly how they’ll measure “severity” and “frequency” to make sure these terms are understood.

- Provide constructive feedback on how the team might be able to improve their project.
  - **Data Quality:** They should explain how they’ll deal with missing or incomplete data, especially for things like mental health indicators or employment information.
  - **List Limitations:** It might help if they list out some possible limitations, like any biases in data or things that are harder to measure accurately (e.g., motivation or mental health).

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
  - It would be interesting to see trends over time and how different states are affected. We are also interested in any findings related to shooter characteristics and incident severity.
  - Including external factors like gun ownership rates could add depth and help show how state-level differences might influence incidents.

- Provide constructive feedback on any issues with file and/or code organization.
  - **Reproducibility:** A README file with explanations on where the data comes from and how the code is set up would make it easier to understand and use.
  - **Dataset Documentation:** They should make sure the datasets are organized and have clear documentation, so it’s easy to understand what each variable means.

- (Optional) Any further comments or feedback?
This project has a lot of potential to provide useful information. We think it would be great if they focused on practical implications in their presentation, like any suggestions for reducing risk factors based on what they find.

Thanks, We loved your Proposal, Best of luck for your project :)

~ team t2c

**Comment by swethakolloju1** [comment]
Hello Team t2c 

I appreciate the thoughtful suggestions on our methods. Here’s how we will address key aspects:

**Linking Datasets:**
The datasets will be combined using the incident_id field as a primary key. This ensures that all relevant information—such as offender demographics, weapon types, and victim details—can be analyzed together.

**Handling Missing Data:**

Numerical values: Missing values will be imputed using the mean or median, depending on the data distribution.
Categorical values: Missing entries will be categorized as “Unknown” to retain the integrity of the dataset.
**Defining Severity and Frequency:**

Severity will be calculated as the total number of casualties in an incident (fatalities + injuries).
Frequency will measure the number of incidents in specific time periods or geographic locations (e.g., yearly counts or state-level distributions).
This structured approach ensures that the analysis remains both robust and reproducible.

**External Factors Clarification**
Regarding the inclusion of state-level variables, such as gun ownership rates, we have decided to work solely with the variables provided in the given datasets. These datasets already offer a wealth of information, such as incident locations, offender characteristics, weapon details, and victim counts. By focusing on these variables, we aim to keep the analysis self-contained and aligned with the scope of our project.

The insights derived will answer the following key research questions:

What are the temporal and geographic trends in mass shooting incidents?
How do offender demographics relate to incident severity?
What patterns can be observed between weapon types and the scale of incidents?
This approach ensures we maximize the utility of the existing datasets without introducing external data sources.

**Data Quality:**

Missing or incomplete data will be handled systematically, as described earlier.
We will ensure that variables across datasets are well-documented for clarity.
Acknowledging Limitations:

Reporting biases (e.g., incomplete demographic data) and missing values will be acknowledged as potential constraints.
Limitations of the variables available in the datasets will be clearly outlined in our findings.
In our presentation, we will focus on the following aspects:

**Trends Over Time and Geography:**
We will use visualizations, such as time series plots and heatmaps, to highlight patterns in the frequency of incidents over time and across states.

**Shooter Characteristics and Severity:**
Demographics like age and gender will be examined alongside the severity of incidents to identify significant patterns.

**Patterns in Weapons and Incidents:**
Relationships between weapon types and the number of casualties will be analyzed to understand their impact on incident outcomes.

We will update the ReadMe file  accordingly 
Thank you for recognizing the potential of this project! We are committed to delivering insights that are both informative and actionable. Your feedback has been invaluable in refining our methods and ensuring clarity in our approach.

~team Data Detective
