### ISSUE TITLE
Review from DreamJobs

### ISSUE THREAD

**Issue by Naveenksaragadam** [INFO-526-FA24/project-2-data-detectivities#10]
The poster is visually appealing, and you did a great job selecting the right type of visualization to tell your story. The descriptive analysis was well executed.

However, there are a few areas for improvement. The first bar chart seems to have some issues with the scale. Additionally, maintaining a consistent color theme throughout the poster would further enhance its visual appeal. The context could be more clearly set to improve the overall message. 

Also, the text accompanying each chart type was a bit difficult to read, and the text wasn't effectively grouped with the visualizations, which made it harder to follow.

**Comment by hema2101UoA** [comment]
The scale of the first bar chart has been corrected, and a consistent color theme has been applied throughout the poster to enhance visual appeal. The context has been clarified to better communicate the overall message.

The accompanying text has been improved for readability and effectively grouped with the respective visualizations, making the poster easier to follow.
