### ISSUE TITLE
Review from 4X4

### ISSUE THREAD

**Issue by tanmaynaik11** [INFO-526-FA24/project-2-data-detectivities#11]
Feedback:
plots are not visible enough can increase the size of the plots and realign the text also change the color coding for seasons.
Good interpretation and storytelling.

**Comment by hema2101UoA** [comment]
The plots have been resized and made more visible, with text realigned for better clarity. The color coding for seasons has been updated to improve distinction. The interpretation and storytelling remain strong and engaging.
