### ISSUE TITLE
Report Feedback - ViZit

### ISSUE THREAD

**Issue by SumelRattan** [INFO-526-FA24/project-2-data-detectivities#12]
Strengths - The visualizations that you used were very creative especially the second plot. Although, we really liked your report, but here are a few improvements that can be made to further enhance it.

Improvements:

- You can improve the scaling of the plots, especially the first plot. 
- The structure of the poster can also be improved, in a way that you need to link the text to their specific plots. Hence, making it more clear for the viewers to understand the overall report. 

Let me know, if you need any help/suggestions. Good job team!

**Comment by hema2101UoA** [comment]
The scaling of the plots, particularly the first one, has been improved for better readability. The poster structure has been refined to clearly link the text with the corresponding plots, enhancing clarity and viewer understanding.
