### ISSUE TITLE
Review by Team Insight Decoders

### ISSUE THREAD

**Issue by hemabk** [INFO-526-FA24/project-2-data-detectivities#13]
Hello Team Data Detectivities

Strengths:
The unique card diagram visualization effectively captures the complexity of mass shooting data in the U.S.
The interpretations are well-explained, making the analysis accessible and engaging.

Weaknesses:
The poster size is not in the proper format, which affects the overall presentation.
While the poster includes numerous visualizations, it could benefit from better layout optimization for clarity.

**Comment by hema2101UoA** [comment]
The poster size has been adjusted to the proper format, enhancing the overall presentation. Additionally, the layout has been optimized to improve the clarity and flow of the visualizations.
