### ISSUE TITLE
Review from Team Insight Spark

### ISSUE THREAD

**Issue by ronymacwan** [INFO-526-FA24/project-2-data-detectivities#14]
The project excels in integrating diverse datasets through a common identifier, ensuring a holistic and consistent analysis of mass shooting incidents across multiple dimensions such as demographics, locations, and weapon details.

We are interested to see:
How the geographic maps and heatmaps visually uncover spatial patterns and correlations in mass shooting incidents across the U.S.

**Comment by hema2101UoA** [comment]
The geographic maps and calendar circular plot now provide clear visual insights, uncovering spatial patterns and correlations in U.S. mass shooting incidents.
