### ISSUE TITLE
Project Peer Review by team Data Nexus

### ISSUE THREAD

**Issue by jolly09-ai** [INFO-526-FA24/project-2-data-detectivities#3]
The following is the peer review of the project proposal by Data Nexus. The team members that participated in this review are 

- Aditya jolly - @jolly09-ai
- Anubhav Mathur - @anubhavbruce
- Nitya Tejaswi Attili - @nityaattili
- Siddheshwar Singh Negi -@SSNEGI1996

- Describe the goal of the project.

The primary goal of the project is to analyze and identify trends, correlations, and patterns in mass shooting incidents across the United States. By studying variables such as time, location, demographics, motivations, and weapon details, the project aims to provide actionable insights for public safety measures and policymaking. The ultimate objective is to uncover factors contributing to such incidents and to suggest strategies for a safer future.

- Describe the data used or collected.

The project utilizes multiple datasets, each offering unique insights into mass shooting incidents:

Incidents Dataset: Contains details on date, location, casualties, incident type, and weapons used.

Offenders Dataset: Includes demographic data, legal outcomes, and other attributes related to the offenders.

Victims Dataset: Provides victim demographics and their relationships with shooters.

Weapons Dataset: Details weapon types, gun classes, and acquisition methods.

These datasets are comprehensive, enabling multidimensional analysis by covering various facets of mass shootings.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The project aims to address four key research questions:

Question 1: Trends in mass shooting incidents over time and geographical variations.

Approach:

Analyze trends by filtering and grouping data by year, month, and state.

Visualize trends using line charts, heatmaps, and geographic maps.

Question 2: Correlation between shooter characteristics and incident severity.

Approach:

Use demographic data (age, gender, race, mental health status, etc.) to identify patterns.

Visualize findings with box plots, correlation plots, and density plots.

Question 3: Temporal patterns of mass shootings.

Approach:

Perform time series analysis to identify patterns by day, week, and month.

Use heatmaps and polar bar plots for visual representation.

Question 4: Influence of motivations and external factors.

Approach:

Correlate motivations (e.g., hate crimes, terrorism) with incident severity and frequency.

Overlay external factors (e.g., gun ownership rates) on choropleth maps to explore trends.

- Is there anything that is unclear from the proposal?

The proposal is well-structured and covers most essential aspects. However, the following areas could use more clarity:

Data Integration: It’s not explicitly mentioned how different datasets (e.g., incidents, offenders, and victims) will be merged or linked.

External Factors: While the proposal mentions using state-level variables like gun ownership rates, it doesn’t specify the source of these external datasets or how they will be integrated.

- Provide constructive feedback on how the team might be able to improve their project.

Detailed Methodology: Provide more detail on the exact preprocessing steps (e.g., handling missing data, cleaning free-text narratives).

Validation Metrics: Include methods for validating the findings, such as cross-referencing with other datasets or statistical significance tests.

Visualization Diversity: Consider using interactive visualizations for presenting the data, such as dashboards using Tableau or Plotly, to enhance audience engagement.

External Variables: Clearly state the sources and integration methods for additional datasets like gun ownership rates.

File and Code Organization: Ensure that the code and datasets are organized into well-labeled directories. Provide a README file for clarity.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The most intriguing aspects of the project include:

Trends and geographical patterns in mass shootings, particularly the use of geographic maps to identify high-risk areas.

Analysis of shooter characteristics and how these correlate with the severity of incidents.

Temporal patterns (e.g., high-risk times) that could provide insights for predictive modeling and public safety measures.

- Provide constructive feedback on any issues with file and/or code organization.

Ensure that all scripts are modular and well-commented.

Maintain clear version control using GitHub, with proper branches for different tasks.

Add detailed documentation and instructions for running analyses to make the project reproducible.

- (Optional) Any further comments or feedback?

The project has significant potential to make impactful contributions to understanding mass shootings and informing public safety measures. The detailed datasets and well-thought-out research questions set a strong foundation. Adding a section on ethical considerations for using sensitive data would further strengthen the proposal.

This is an excellent initiative with the potential to provide meaningful insights into a critical societal issue.

**Comment by swethakolloju1** [comment]
Thank you for your detailed review and valuable feedback. We appreciate your insights and will address the points raised to strengthen our project.

The primary goal of our project is to analyze trends, correlations, and patterns in mass shooting incidents across the U.S., focusing on variables like time, location, demographics, and motivations. Our aim is to uncover insights that can inform public safety measures and policy decisions. 

We will be using four key datasets: **Incidents**, **Offenders**, **Victims**, and **Weapons**, which provide detailed information on each incident, the offenders, and the victims. These datasets will be integrated using the `incident_id` field, ensuring that all relevant data is linked properly for analysis. We decided to exclude external datasets like gun ownership rates to maintain a focused analysis with the data we already have.

For answering our research questions, we plan to analyze trends over time and across geographic areas, using visualizations like line charts and heatmaps. We will also explore the correlation between shooter characteristics and incident severity, and investigate temporal patterns using time series analysis. Motivations for the incidents will be examined and correlated with severity and frequency, based on available data.

Regarding the data integration, we will merge the datasets using the common `incident_id`, ensuring the data is linked accurately. We’ve chosen not to incorporate external factors like gun ownership rates to keep the project focused on the datasets at hand.

We will include more detail on the preprocessing steps and validation methods, such as handling missing data and performing statistical significance tests to ensure the findings are reliable. We will also organize the code and datasets clearly, making the project reproducible with proper documentation.

Thank you again for your feedback. We’re excited to refine our project and look forward to delivering meaningful insights on this important issue.

~team Data Detectives
