### ISSUE TITLE
Instructor feedback

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-data-detectivities#4]
Hello team Data Detectives - 

Great job at addressing the issues brought forward by the peer review. 
After reviewing your proposal, I believe that your team is set up for a success. The data set will answer the proposed research questions. The analysis and visualizations should address the research questions. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |    3    |
| Proposal | 5         |   5     |
| Workflow | 1         |    1    |
| Teamwork | 1         |     1   |
| Total    | 10        |   10     |

**Comment by swethakolloju1** [comment]
Thank you professor for the feedback
