### ISSUE TITLE
Poster Peer Review

### ISSUE THREAD

**Issue by Sahana2699** [INFO-526-FA24/project-2-data-detectivities#5]
Overall, the analysis is well-executed, and the visualizations are impressive. The chord diagram and choropleth map are particularly effective in presenting the data.
The heat map color scheme needs adjustment to improve clarity, making differences and observations more distinct and easily visible.

**Comment by hema2101UoA** [comment]
The heat map no longer uses unnecessary colors, and the world map's color scheme has been improved for better clarity and aesthetics.
