### ISSUE TITLE
Poster review by DataWaves

### ISSUE THREAD

**Issue by Saharsh-Bhave** [INFO-526-FA24/project-2-data-detectivities#7]
### 1. What is the good thing in the poster?
The dataset used by this team is about US mass shootings. They have made good observations and inferences from the data.

### 2. What do you think can/should be improved?
The heatmap legend's color scale can be reversed so that the lighter color denotes safer areas, and the darker color depict the unsafe or more shooting prone areas.

**Comment by hema2101UoA** [comment]
The heatmap legend's color scale has been reversed, with lighter colors now representing safer areas and darker colors indicating more shooting-prone areas, improving visual intuitiveness.
