### ISSUE TITLE
Review from Visual Voyagers

### ISSUE THREAD

**Issue by Tusharvimal** [INFO-526-FA24/project-2-data-detectivities#8]
1. What is the good thing in the poster?
The Dataset and the plots shown are pretty good and engaging.

2. What do you think can/should be improved?
The coord plot is hard to interpret and data to ink ratio could be better.

**Comment by hema2101UoA** [comment]
The chord plot has been simplified to improve interpretability, and adjustments have been made to enhance the data-to-ink ratio, ensuring a clearer and more efficient visualization.
